Update dabble to be Python 3 compatible!
Minor changes, xrange->range, filter, iteritems, etc.
Changes to imports for networkx >= 1.11
Added required packages in install_requires in setup.py
Change imports for test cases so they all pass in python 3
exception: Issue #16 has charmm disulfides failing!!!